version: "3.9"

services:

  frontend:
    image: nginx:1.22
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/static:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api-service


  todo-api-service:
    build: ./backend
    environment:
      STORAGE: mysql
      MYSQL_HOST: db
      MYSQL_USER: todo-user
      MYSQL_PWD: "password"
      MYSQL_DB: "examen"
    depends_on:
      - db

  db:
    environment:
      MYSQL_DATABASE: "examen"
      MYSQL_USER: todo-user
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
    image: mysql:8.0.29-debian
    platform: linux/x86_64
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mydata:/var/lib/mysql




volumes:
  mydata:

